# Site settings
title: Theodore S. Lindsey
baseurl: "" # the subpath of your site, e.g. /blog
# for rss, etc
name: Theodore S. Lindsey
url: "http://theodorelindsey.io" # the base hostname & protocol for your site
description: > # this means to ignore newlines until "baseurl:"
  Personal and professional website for Theodore S. Lindsey.

# usernames
username_twitter: RagingRoosevelt
username_github: RagingRoosevelt
username_gplus: +TheodoreSatchLindsey
username_linkedin: theodorelindsey
username_steam: RagingRoosevelt
username_facebook: theodore.lindsey

# contact info
phone: "(503) 898-0184"
email: theodore.lindsey@gmail.com
office: Montgomery Park, Portland

timezone: America/Chicago

# blog post url format
permalink: /blog/:year/:month/:day/:title.html
paginate: 5
paginate_path: "/blog/page:num/"
