# Site settings
title: Theodore S. Lindsey
baseurl: "" # the subpath of your site, e.g. /blog/
# for rss, etc
name: Theodore S. Lindsey
url: "http://theodorelindsey.io" # the base hostname & protocol for your site
description: > # this means to ignore newlines until "baseurl:"
  Personal and professional website for Theodore S. Lindsey.

# usernames
username_twitter: RagingRoosevelt
username_github: RagingRoosevelt
username_gplus: +TheodoreSatchLindsey
username_linkedin: theodorelindsey
username_steam: RagingRoosevelt
username_facebook: theodore.lindsey

# contact info
phone: "(503) 898-0184"
email: theodore@theodorelindsey.io
office: Eaton 2029
hours: "<ul style=\"padding: 0px; margin: 0px; margin-top: 1em\"><li>T 12:30pm - 14:15pm</li><li>W 9:00am - 9:50am</li><li>W 11:00am - 11:50am</li><li>by appointment</li></ul>"

# Build settings
markdown: kramdown
pygments: true

timezone: America/Chicago

# blog post url format
permalink: /blog/:year/:month/:day/:title.html
paginate: 5
paginate_path: "/blog/page:num/"
