# Site settings
title: Theodore S. Lindsey
baseurl: "" # the subpath of your site, e.g. /blog
# for rss, etc
name: Theodore S. Lindsey
url: "http://theodorelindsey.io" # the base hostname & protocol for your site
description: > # this means to ignore newlines until "baseurl:"
  Personal and professional website for Theodore S. Lindsey.
repository: RagingRoosevelt/RagingRoosevelt.github.io

# usernames
username_twitter: RagingRoosevelt
username_github: RagingRoosevelt
username_gplus: +TheodoreSatchLindsey
username_linkedin: theodorelindsey
username_steam: RagingRoosevelt
username_facebook: theodore.lindsey

# contact info
phone: "(503) 745-8444"
email: me@theodore.io
office: Montgomery Park, Portland
office_link: "https://www.google.com/maps/place/2701 NW Vaughn St, Portland, OR 97210"

timezone: America/Los_Angeles

collections:
  book_reviews:
    output: true

future: false
show_drafts: false
# blog post url format
permalink: /blog/:year/:month/:day/:title.html
paginate: 5
paginate_path: "/blog/page:num/"
excerpt_separator: <!--more-->

kramdown:
  syntax_highlighter_opts:
    line_numbers : false


plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-seo-tag
