# Site settings
title: Theodore S. Lindsey
email: theodore@theodorelindsey.com
description: > # this means to ignore newlines until "baseurl:"
  Personal and professional website for Theodore S. Lindsey.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://theodorelindsey.com" # the base hostname & protocol for your site

# usernames
username_twitter: RagingRoosevelt
username_github: RagingRoosevelt
username_gplus: +TheodoreSatchLindsey
username_linkedin: theodorelindsey
username_steam: RagingRoosevelt
username_facebook: theodore.lindsey

# Build settings
markdown: kramdown

timezone: America/Chicago